---
title: "MIL2-Project2"
author: "Catherine Young"
date: "2024-10-14"
output: pdf_document
---


```{r}
#load in original dataset 
dataset<-read.csv("C:/Users/young/OneDrive/Desktop/DS 4002/IDB_10-21-2024.csv")
head(dataset)
```


```{r}
#load in tidyr to remove nas
library(tidyr)
df1<- dataset %>% fill(Total.Fertility.Rate, .direction = 'up')
df2<- df1 %>% fill(Crude.Birth.Rate, .direction = 'up')
df3<- df2 %>% fill(Net.Migration.Rate, .direction = 'up')
df4<- df3 %>% fill(Crude.Death.Rate, .direction = 'up')
clean_df<- df4 %>% fill(Net.international.migrants..both.sexes, .direction = 'up')
head(clean_df)
```

```{r}
#load needed package 
library(ggplot2)

#time series plot on pop 
ggplot(clean_df, aes(x=Year, y=Population, color=Name, group=Name)) +
  geom_line(size=1.2) +
  geom_point(size=3) +
  labs(title="Population Trends from 2000-2024",
       x="Year",
       y="Population",
       color="Country") +
  scale_x_continuous(breaks=1) +
  theme_minimal() +
  theme(axis.text.x=element_text(angle=45, hjust=1))

#save the graph as image
ggsave("population_trends.png", width = 10, height = 6)
```



```{r}
#create the scatter plot for Net Migration Rate on Year
ggplot(clean_df, aes(x=Year, y=`Net.Migration.Rate`, color=Name, group=Name)) +
  geom_point(size=3) +
  geom_line(size=1.2) +
  labs(title ="Net Migration Rate Years (2000-2024)",
       x="Year",
       y="Net Migration Rate",
       color="Country") +
  scale_x_continuous(breaks=1) +
  theme_minimal()

#save the graph as image
ggsave("net_migration_rate.png", width = 10, height = 6)
```


```{r}
#clean the data. Read in the dataset with values entered for nas
clean_data<-read.csv("C:/Users/young/OneDrive/Desktop/DS 4002/IDB_10-07-2024_clean.csv")
filtered_data_clean<- clean_data[clean_data$Year %in% c(2019, 2020, 2021), ]
head(filtered_data_clean)
```




```{r}
#scatterplot on: Net Migration Rate vs Crude Death Rate
ggplot(clean_data, aes(x=`Crude.Death.Rate`, y=`Net.Migration.Rate`, color=Name)) +
  geom_point(size=3) +  
  geom_smooth(method="lm", se=FALSE, color="black", aes(group=Name)) + #adds line of best fit
  labs(title= "Net Migration Rate vs Crude Death Rate",
       x= "Crude Death Rate",
       y= "Net Migration Rate",
       color= "Country") +
  theme_minimal()

#save the graph as image
ggsave("net_migration_vs_crude_death_rate.png", width= 10, height = 6)
```

```{r}
#scatterplot on: Life Expectancy vs Crude Death Rate
ggplot(clean_data, aes(x=`Crude.Death.Rate`, y= `Life.Expectancy.at.Birth..Both.Sexes`,color=Name)) +
  geom_point(size = 3) +  
  geom_smooth(method="lm", se=FALSE, color="black",aes(group=Name)) +   #adds line of best fit
  labs(title = "Life Expectancy vs Crude Death Rate",
       x= "Crude Death Rate",
       y= "Life Expectancy",
       color= "Country") +
  theme_minimal()

#save the graph as image
ggsave("life_expectancy_vs_crude_death_rate.png", width=10, height= 6)
```

```{r}
#scatterplot on: Total Fertility Rate vs Crude Death Rate
ggplot(clean_data, aes(x=`Crude.Death.Rate`, y=`Total.Fertility.Rate`, color=Name)) +
  geom_point(size=3) + 
  geom_smooth(method="lm", se=FALSE, color="black", aes(group=Name)) +   #adds line of best fit
  labs(title = "Fertility Rate vs Crude Death Rate",
       x= "Crude Death Rate",
       y= "Fertility Rate",
       color= "Country") +
  theme_minimal()

#save the graph as image
ggsave("fertility_rate_vs_crude_death_rate.png", width=10, height=6)
```






